### PR TITLE
Move theme-toggle styles into external css

### PR DESCRIPTION
**Pull request by zoglo**
### TL;DR

- invalid HTML

### Description

Fritz mentioned that the `<style>` attribute wasn't valid HTML within `<body>`.
This PR addresses this issue and introduces the config.toml for adding custom css to the hugo learn theme https://learn.netlify.app/en/basics/configuration/ and splits the css from the current component into a `theme-toggle.css`.

_(Yeah, this will be fixed in the contao docs as well :) )_

### CODE REVIEW

**Comment by aschempp** [comment]
We already have a lot of custom CSS in `theme-terminal42.css`, why would we need a separate file for this?

**Comment by zoglo** [comment]
Trying to keep it separate as a component (see mermaid CSS and all the other styles in the Hugo theme). Do you think it's best in the custom-theme that currently only holds the colors?

**Comment by aschempp** [comment]
idk, maybe we could also import it there? Isn't the theme toggle part of our custom theme/HTML etc. anyway?

**Comment by zoglo** [comment]
It technically is part of the theme, I don't mind moving it there since it would make sense to load with it anyway.
I was rather thinking about the component.css approach that the whole Hugo-theme offers and didn't want to merge it with the theme css that was mostly just used to adjust colors / add custom properties for colors.

I'd be fine with either, it's simply that the current implementation is not valid.

**Comment by aschempp** [comment]
I guess we'll just keep whatever the Contao documentation does, that's the most simple approach 😅

**Comment by zoglo** [comment]
Meaning it'll be moved into external CSS like this PR :)

**Comment by zoglo** [comment]
@aschempp see https://github.com/contao/docs/pull/1386

**Comment by aschempp** [comment]
Thank you @zoglo

**Pull request merged**
